# Form implementation generated from reading ui file 'windows/mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(767, 428)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(parent=self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.fileTree = QtWidgets.QTreeWidget(parent=self.splitter)
        self.fileTree.setHeaderHidden(True)
        self.fileTree.setObjectName("fileTree")
        self.fileTable = QtWidgets.QTableView(parent=self.splitter)
        self.fileTable.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.MultiSelection)
        self.fileTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.fileTable.setObjectName("fileTable")
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 767, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(parent=self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(parent=MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.syncNowAction = QtGui.QAction(parent=MainWindow)
        self.syncNowAction.setObjectName("syncNowAction")
        self.settingsAction = QtGui.QAction(parent=MainWindow)
        self.settingsAction.setObjectName("settingsAction")
        self.menu.addAction(self.syncNowAction)
        self.menu.addAction(self.settingsAction)
        self.menubar.addAction(self.menu.menuAction())
        self.toolBar.addAction(self.syncNowAction)
        self.toolBar.addAction(self.settingsAction)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Yandex.Диск v.1.0"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.syncNowAction.setText(_translate("MainWindow", "Синхронизировать"))
        self.syncNowAction.setToolTip(_translate("MainWindow", "Синхронизировать сейчас"))
        self.settingsAction.setText(_translate("MainWindow", "Параметры"))
        self.settingsAction.setToolTip(_translate("MainWindow", "Настройка параметров программы"))
